### PR TITLE
feat: host swagger UI at v4.loopback.io/api-explorer

### PR DESCRIPTION
**Pull request by raymondfeng**
This PR allows API Explorer to be served from:

http://v4.loopback.io/api-explorer (for http://localhost:3000/openapi.json)
https://v4.loopback.io/api-explorer (for https://localhost:3000/openapi.json)

It can be then used to fix https://github.com/strongloop/loopback-next/issues/1603

### CODE REVIEW

**Comment by bajtos** [comment]
To be honest, I am not very happy about maintaining two copies of swagger-ui (on at `loopback.io`, another at `v4.loopback.io`). The fact that `v4.loopback.io` does not automatically redirect from HTTP to HTTPS looks like an oversight to me, one that we should fix soon. Once that change is done, I don't see any value in this second swagger-ui copy at `v4.loopback.io`.

On the other hand, if we think that HTTP->HTTPS redirect is not that important, then surely we can disable the redirect for `loopback.io` too and use the original swagger-ui version hosted there for both HTTP & HTTPS apps.

Thoughts?

cc @virkt25

**Comment by hacksparrow** [comment]
This is a temporary thing, right? Finally API Explorer would be self-hosted in the user's app, yes?

**Comment by raymondfeng** [comment]
> To be honest, I am not very happy about maintaining two copies of swagger-ui (on at loopback.io, another at v4.loopback.io).

We don't want to maintain two copies. The idea was to move `api-explorer` to `v4.loopback.io` so that it can be served with either http or https.

**Comment by raymondfeng** [comment]
I see three options to allow the hosted API explorer to serve `http://.../openapi.json`:

1. Disable `https` redirect for `http` on `loopback.io` so that we can serve the API Explorer as `http://loopback.io/api-explorer`.

2. Land this PR so that we can serve the API Explorer as `http://v4.loopback.io/api-explorer`.

3. Create a new sub-domain and new repo such as `explorer.loopback.io` and serve the API Explorer as `http://explorer.loopback.io`.

**Comment by virkt25** [comment]
I had left a comment on Slack, let me paste it here:

> And I thought the plan was to have that redirect to loopback.io eventually. I think we need a `explorer.loopback.io` to support http/https. v4.loopback.io not having the same https config as `loopback.io` is an oversight imo.

Also I thought as per the agreement on https://github.com/strongloop/loopback-next/issues/1603, we were going to make an `explorer.loopback.io` for our hosted version of the explorer and remove the one from `loopback.io/api-explorer` so we are only maintaining one copy.

**Comment by bajtos** [comment]
> Also I thought as per the agreement on https://github.com/strongloop/loopback-next/issues/1603, we were going to make an `explorer.loopback.io` for our hosted version of the explorer and remove the one from `loopback.io/api-explorer` so we are only maintaining one copy. 

Yes, that was my understanding too!

I think this maps to the third option described by @raymondfeng in his comment:
> Create a new sub-domain and new repo such as `explorer.loopback.io` and serve the API Explorer as `http://explorer.loopback.io`.

**Comment by raymondfeng** [comment]
I was in the agreement to option 3 (create explorer.loopback.io domain/github repo to serve LoopBack API explorer over both http and https). But after I tried to bring it up with v4.loopback.io, I have a few questions now:

1. Is it worth the effort to create a separate domain/repo for the API explorer instead of hosting it on v4.loopback.io? Please note that we can still have `explorer.loopback.io` pointing to `v4.loopback.io/api-explorer`, right?

2. What's the UI branding and site analytics? It would be ideal for the API Explorer to be consistent with LoopBack V4 scheme. Having two sites complicate things for sure. How do we promote v4.loopback.io from the Explorer page?

3. Is it possible to exclude `http` to `https` redirect for certain paths? For example, leave `http://v4.loopback.io/api-explorer` as it while forcing https for the rest.

4. Do we have vision to create other hosted UIs, such as dashboard for appmetrics?

@rmg What's your view from operational perspective?

**Comment by virkt25** [comment]
> Is it worth the effort to create a separate domain/repo for the API explorer instead of hosting it on v4.loopback.io? Please note that we can still have explorer.loopback.io pointing to v4.loopback.io/api-explorer, right?

I personally think it's worth the effort as the hosted site will be version agnostic. I don't think pointing `explorer.loopback.io` to `v4.loopback.io/api-explorer` is a good idea. The biggest area for concern here is the fact that the plan is for `v4.loopback.io` to redirect to `loopback.io` and it will become the main site when LB4 GA's. 

> What's the UI branding and site analytics? It would be ideal for the API Explorer to be consistent with LoopBack V4 scheme. Having two sites complicate things for sure. How do we promote v4.loopback.io from the Explorer page?

I would like to see the explorer switch branding to the new LB4 theme BUT this would be a low priority issue IMO that we can work on later on down the road and for now it can be what it is right now. As for Analytics, we current are using IBM Tealium scripts ... which actually doesn't work for `v4.loopback.io` -- I'll ping the team to allow requests from this domain to the analytics site. We also still haven't figured out how to get access to these analytics yet ... but we might be able to go back to Google Analytics (I'll try and follow up on this for an update). 

> Is it possible to exclude http to https redirect for certain paths? For example, leave http://v4.loopback.io/api-explorer as it while forcing https for the rest.

Not for a `/path` AFAIK but this is probably best answered by @rmg 

> Do we have vision to create other hosted UIs, such as dashboard for appmetrics?

Maybe? ... Depends on the tools. I think a dashboard would have to be a self-hosted component as we won't have access to the site analytics if we host it.

**Comment by raymondfeng** [comment]
> I personally think it's worth the effort as the hosted site will be version agnostic. I don't think pointing explorer.loopback.io to v4.loopback.io/api-explorer is a good idea. The biggest area for concern here is the fact that the plan is for v4.loopback.io to redirect to loopback.io and it will become the main site when LB4 GA's.

Promoting `v4.loopback.io` to `loopback.io` does not impact how `explorer.loopback.io` works as we can always update DNS.

> I think a dashboard would have to be a self-hosted component as we won't have access to the site analytics if we host it.

`appmetrics-dashboard` UI uses websocket to communicate with the host. The hostname is not configurable at the moment, but it should be an easy fix.

**Comment by virkt25** [comment]
> Promoting v4.loopback.io to loopback.io does not impact how explorer.loopback.io works as we can always update DNS.

Yes we can but I think it's better to just have an endpoint that's not going to keep changing or redirecting since we'll already be looking to redirect `/swagger-ui` to `explorer.loopback.io`. I like the idea of a consistent domain the users can count on regardless of the version of loopback down the road. 

I guess let me ask what is this instead, what is the benefit of going with `/explorer` besides one less repository? (It's not touched often enough so it's ok imo).

**Comment by raymondfeng** [comment]
> I guess let me ask this instead, what is the benefit of going with /explorer besides one less repository? (It's not touched often enough so it's ok imo).

It's easier to maintain one site with consistent look and feel, common headers/footers, and one way of creating pages (Jekyll or VuePress).

**Comment by rmg** [comment]
From a hosting perspective, when using GitHub Pages, we are restricted to 1 CNAME per repo. If we want `v4.loopback.io`, `explorer.loopback.io`, and `loopback.io` then that requires 3 separate repos.

From a consumer/developer perspective, I'm surprised that explorer isn't hosted via 4 hard-coded route handlers. The generic static asset support seems overkill for something that is only 4 files and has been the same 4 files for quite a while (as far as I can tell).

My biggest concern, however, is that if we host it people will expect it to be reliable and then start relying on it to be there. Changing it in the future would be harder and harder since the ones that rely on it the most would likely be the ones that are less likely to keep up to changes.

**Comment by virkt25** [comment]
> It's easier to maintain one site with consistent look and feel, common headers/footers, and one way of creating pages (Jekyll or VuePress).

I agree but the explorer comes in as a 3rd party component which we want to customize and to do so we would have to override their styles anyways so the styles won't be shared. We'd be able to reuse the variables ... but the explorer would need it's own CSS overrides. And not sure if there's much for a static site generator to do with this page. 

I'm not super opposed to this, just this the other approach might be better. If we are going down this route then let's keep in mind that `v4.loopback.io` not defaulting to https is an oversight. If it's possible for us to serve `/api-explorer` over http / https while defaulting all other pages to https then I'm ok and would prefer to see this done for `loopback.io/api-explorer` since `v4.loopback.io/api-explorer` will eventually become the first domain and I don't think we will be styling the explorer anytime before the change is made.

**Comment by raymondfeng** [comment]
@rmg We're working on an explorer component for LoopBack so that the UI can be hosted with the application itself - https://github.com/strongloop/loopback-next/pull/1664.

The hosted UI was a workaround before we introduced static asset serving capability in LB4.

**Comment by rmg** [comment]
The kinds of controls (http vs https, path specific handling, etc.) I'm seeing discussed here are not things that can be reliably controlled with free hosting.

If these sorts of things are required/expected then someone will have to pay for it.

**Comment by b-admike** [comment]
> I don't have very strong opinions either. Just try to get it done quicker to unblock [strongloop/loopback-next#1603](https://github.com/strongloop/loopback-next/issues/1603). Not being able to use the explorer is pretty bad for our users.

@raymondfeng should we review that PR instead of this one and focus on getting that landed?

**Comment by bajtos** [comment]
Let's close this one in favor of https://github.com/strongloop/explorer.loopback.io/pull/1 which publishing the API explorer at the hostname `explorer.loopback.io`.

**Pull request closed without merging**
