### PR TITLE
add demo video

### PR DESCRIPTION
**Pull request by dhmlau**
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>

Add demo video to showcase how to create REST APIs with just 5 steps.  
Eventually, I think we want to have a page for presentations and videos in the LB4 web site.

related: https://github.com/strongloop/v4.loopback.io/issues/47

### CODE REVIEW

**Comment by raymondfeng** [comment]
IMO, github is not the best place to host videos. Should we upload it to YouTube and embed in v4.loopback.io site?

**Comment by dhmlau** [comment]
I've checked with the IBM Developer editor. They actually are using YouTube https://www.youtube.com/user/developerworks.  
An alternative I see others are using is [Vimeo](https://vimeo.com/).

**Comment by bajtos** [comment]
> I've checked with the IBM Developer editor. They actually are using YouTube https://www.youtube.com/user/developerworks.
An alternative I see others are using is Vimeo.

Fair enough 🤷‍♂️

**Comment by dhmlau** [comment]
Closing this PR as irrelevant.  
- Got feedback from @bajtos on the video
   - add narrative
   - more descriptive datasource name
   - look into the security vulnerability when running `lb4 app`, which @raymondfeng has a PR up already.
- When it's ready, will post the video on YouTube instead in our github repo.

**Pull request closed without merging**
